CREATE TABLE STATUS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE FUNCIONARIO (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_FUNC VARCHAR(255) NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE INT (11) NOT NULL,
EMAIL VARCHAR(255),
ID_EMPRESA INT NOT NULL,
ID_CARGO INT NOT NULL,
DATA_ADMISSAO DATE NOT NULL,
DATA_DEMISSAO DATE,
ID_STATUS INT NOT NULL,
VALOR DECIMAL(8,2)
);

CREATE TABLE EMPRESA (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_EMPRESA VARCHAR(255),
CNPJ BIGINT NOT NULL
);

INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ) VALUES ("KELVIN CONSTRUCAO CIVIL LTDA",9999999999999);
INSERT INTO EMPRESA (NOME_EMPRESA, CNPJ) VALUES ("KELVIN LOGISTICA LTDA",9999999999998);

CREATE TABLE CARGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_CARGO VARCHAR(255),
ID_EMPRESA INT NOT NULL
);

ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID);
ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID);
ALTER TABLE CARGOS ADD FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("PEDREIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("CARPINTEIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MARCENEIRO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ELETRECISTA",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("AJUDANTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SERRALHEIRO",1);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MOTORISTA",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("MOTOBOY",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("AJUDANTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("OPERADOR DE EMPILHADEIRA",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("OPERADOR DE MAQUINAS",2);

INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("GERENTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SUPERVISOR",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ASSISTENTE",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ENCARREGADO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DIRETOR",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DONO",1);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("GERENTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("SUPERVISOR",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ASSISTENTE",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("ENCARREGADO",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DIRETOR",2);
INSERT INTO CARGOS (NOME_CARGO, ID_EMPRESA) VALUES ("DONO",2);

INSERT INTO STATUS (NOME_STATUS) VALUES ("ATIVO");
INSERT INTO STATUS (NOME_STATUS) VALUES ("DEMITIDO");
INSERT INTO STATUS (NOME_STATUS) VALUES ("AFASTADO");